### PR TITLE
Remove duplicate condition

### PR DESCRIPTION
**Pull request by eliaslfox**

### CODE REVIEW

**Review by phoe — COMMENTED** [review]
https://github.com/coalton-lang/coalton/runs/4371173304?check_suite_focus=true

```lisp
; file: /home/runner/work/coalton/coalton/src/toplevel-define.lisp
; in: DEFUN COALTON-IMPL::PARSE-DEFINE-FORM
;     (COALTON-IMPL::ERROR-PARSING COALTON-IMPL::FORM
;      "Found a null value where a symbol or function ~
;                               was expected.")
; 
; caught STYLE-WARNING:
;   undefined function: COALTON-IMPL::ERROR-PARSING
; 
; compilation unit finished
;   Undefined function:
;     COALTON-IMPL::ERROR-PARSING
;   caught 14 STYLE-WARNING conditions
;   printed 256 notes
```

Seems like this function was not unused.

**Comment by eliaslfox** [comment]
This is fixed now.

**Comment by phoe** [comment]
The only nitpick I can see in the build logs right now is:

```lisp
2021-11-30T17:52:31.2720444Z ; file: /home/runner/work/coalton/coalton/src/typechecker/parse-class-definition.lisp
2021-11-30T17:52:31.2721565Z ; in: DEFUN PARSE-CLASS-DEFINITIONS
2021-11-30T17:52:31.2722343Z ;     (MULTIPLE-VALUE-BIND
2021-11-30T17:52:31.2723374Z ;         (CLASS COALTON-IMPL/TYPECHECKER::METHODS
2021-11-30T17:52:31.2724371Z ;          COALTON-IMPL/TYPECHECKER::DOCSTRING)
2021-11-30T17:52:31.2725493Z ;         (COALTON-IMPL/TYPECHECKER::PARSE-CLASS-DEFINITION
2021-11-30T17:52:31.2726746Z ;          COALTON-IMPL/TYPECHECKER::FORM COALTON-IMPL/TYPECHECKER::ENV)
2021-11-30T17:52:31.2727815Z ;       (SETF COALTON-IMPL/TYPECHECKER::ENV
2021-11-30T17:52:31.2728987Z ;               (COALTON-IMPL/TYPECHECKER:SET-CLASS COALTON-IMPL/TYPECHECKER::ENV
2021-11-30T17:52:31.2730042Z ;                                                   (COALTON-IMPL/TYPECHECKER:TY-CLASS-NAME
2021-11-30T17:52:31.2730666Z ;                                                    CLASS)
2021-11-30T17:52:31.2731116Z ;                                                   CLASS))
2021-11-30T17:52:31.2732031Z ;       (DOLIST (METHOD COALTON-IMPL/TYPECHECKER::METHODS)
2021-11-30T17:52:31.2733032Z ;         (SETF COALTON-IMPL/TYPECHECKER::ENV
2021-11-30T17:52:31.2733879Z ;                 (COALTON-IMPL/TYPECHECKER:SET-VALUE-TYPE
2021-11-30T17:52:31.2735103Z ;                  COALTON-IMPL/TYPECHECKER::ENV # #))
2021-11-30T17:52:31.2736080Z ;         (SETF COALTON-IMPL/TYPECHECKER::ENV
2021-11-30T17:52:31.2737242Z ;                 (COALTON-IMPL/TYPECHECKER:SET-NAME COALTON-IMPL/TYPECHECKER::ENV
2021-11-30T17:52:31.2737931Z ;                                                    # #))
2021-11-30T17:52:31.2738677Z ;         (IF (COALTON-IMPL/TYPECHECKER:FUNCTION-TYPE-P
2021-11-30T17:52:31.2739819Z ;              (COALTON-IMPL/TYPECHECKER::QUALIFIED-TY-TYPE #))
2021-11-30T17:52:31.2740405Z ;             (LET (#)
2021-11-30T17:52:31.2740775Z ;               (SETF #))
2021-11-30T17:52:31.2741612Z ;             (SETF COALTON-IMPL/TYPECHECKER::ENV #)))
2021-11-30T17:52:31.2742109Z ;       CLASS)
2021-11-30T17:52:31.2742454Z ; 
2021-11-30T17:52:31.2742982Z ; caught STYLE-WARNING:
2021-11-30T17:52:31.2743591Z ;   The variable DOCSTRING is defined but never used.
2021-11-30T17:52:31.3033709Z ; processing (DEFUN PARSE-CLASS-DEFINITIONS ...)
2021-11-30T17:52:31.3221186Z ; processing (DEFUN PARSE-CLASS-DEFINITION ...)
2021-11-30T17:52:31.3266497Z WARNING:
2021-11-30T17:52:31.3267532Z    Lisp compilation had style-warnings while
2021-11-30T17:52:31.3268683Z    compiling #<CL-SOURCE-FILE "coalton" "typechecker" "parse-class-definition">
```

LGTM

**Review by colescott — APPROVED** [review]
Good catch. I think this comes back to something that has been needing some extra attention in the codebase with how we handle and propagate parsing errors. 

There is a lot of code that goes in to parsing different parts of type signatures (in `src/typechecker/parse-*.lisp`) and the coalton AST (in `src/ast/parse-form.lisp`) that relies on a bit of :spaghetti: with what I would call less than ideal source tracking and error propagation. In the future it would be great to unify at least some of the error tracking code for these.
This is definitely beyond the scope of this PR but I just wanted to include a bit of context.

**Comment by stylewarning** [comment]
@eliaslfox The branch needs to be rebased. Maybe you can add an IGNORE decl and then we can merge.

Also CI has that pesky 5th item again that doesn't resolve.

**Comment by eliaslfox** [comment]
@stylewarning fixed

**Pull request merged**
