### PR TITLE
allegro compat

### PR DESCRIPTION
**Pull request by eliaslfox**
This pr does several things:
* Add allegro specific corrections for floating point math
* Removes the unmaintained coalton-json example. It had non-portable tests that asserted the printed representation of floats.
* A few other minor fixes

This is dependent on #779

### CODE REVIEW

**Comment by eliaslfox** [comment]
Changed `math:expt` to return nan when given a negative base.

**Review by colescott — APPROVED** [review]
Looks good.

**Comment by colescott** [comment]
Are there any plans for adding Allegro to the CI pipeline?

**Comment by gefjon** [comment]
> Are there any plans for adding Allegro to the CI pipeline?

If y'all haven't already, someone (i.e. @stylewarning) should reach out to Franz and ask about that.

**Pull request merged**
