### PR TITLE
Add CCL support

### PR DESCRIPTION
**Pull request by eliaslfox**
The tests run locally in ccl. CI support isn't added yet. Masking float traps is required as mentioned in https://github.com/coalton-lang/coalton/issues/778#issuecomment-1422675106.

### CODE REVIEW

**Comment by gmpalter** [comment]
Just thought I'd mention that, in CCL, the form `(pathname-type *.fasl-pathname*)` will give you the correct file type for whatever hardware platform CCL is running on.

**Comment by eliaslfox** [comment]
I ran into two issues with NaN values in CCL.
* https://github.com/Clozure/ccl/issues/440
* https://github.com/Clozure/ccl/issues/441

Neither is technically blocking as Coalton's tests run on CCL currently. The first one we could correct within Coalton by explicitly checking for NaN values in Coalton's comparison functions. The second one can be avoided by disabling float traps.

**Comment by eliaslfox** [comment]
CI is failing because Github Actions can't pull a docker container. Pulling locally works, so I think the runner cached a permission failure.

**Comment by colescott** [comment]
The Github actions permission issue seems to have solved itself. Now it looks like we just need to disable floating point traps either by default in Coalton or add that to the tests.

Additionally, it looks like CCL is not returning a non-zero on failure. I don't see anything in the docs about this but I suspect using `--batch` might get the behavior we want.

**Review by colescott — APPROVED** [review]

**Pull request merged**
