### PR TITLE
Fix: codegen appends Unit expr onto loop bodies.

### PR DESCRIPTION
**Pull request by macrologist**
Addresses #1021

### CODE REVIEW

**Review by stylewarning — APPROVED** [review]
I object to the name "force-unit" but I don't immediately have a better alternative.

**Comment by macrologist** [comment]
> I object to the name "force-unit" but I don't immediately have a better alternative.

If @eliaslfox doesn't object to the approach, I can rename it something like 

`(append-unit-expr <node>)` or something

**Review by eliaslfox — APPROVED** [review]
I like `append-unit`.

**Comment by eliaslfox** [comment]
@macrologist did you figure out why the behavior was different in `coalton-codegen`?

**Comment by macrologist** [comment]
@eliaslfox 
> @macrologist did you figure out why the behavior was different in `coalton-codegen`?

Sort of. The specialization of `typecheck-node` on `node-bind` unifies the `node-bind`'s expression type with it's body's  type.  Looking at it again I see that typecheck-node returns a type, and that recursive invocations rely on that return type: I did not realize this earlier. 

I think that the loop nodes should all return unit from typecheck-node but aren't. They're returning the type of the body.

Perhaps this PR should be reverted in favor altering typecheck-node instead. Or perhaps both -- though both would be a little redundant. My preference would be to drop these commits and alter typecheck-node.

**Comment by macrologist** [comment]
(a bit more verbiage) From the perspective of correctness, afaict, the choice is fairly arbitrary. From the perspective of performance, killing these commits in favor of altering typecheck-node seems better. But maybe I'm wrong about correctness?

**Comment by eliaslfox** [comment]
> killing these commits in favor of altering typecheck-node seems better

This seems like a better solution.

**Pull request merged**
