### PR TITLE
add JSON parser example

### PR DESCRIPTION
**Pull request by stylewarning**
This adds an example piggybacking off of an existing JSON library.

### CODE REVIEW

**Comment by stylewarning** [comment]
Tests pass locally with `make test`.

**Comment by stylewarning** [comment]
The build error happens because this commit adds a new dependency `json-streams` which isn't being downloaded by the test runner:

```
  An unhandled error condition has been signalled:
     Component #:JSON-STREAMS not found, required by #<SYSTEM "coalton-json">
```

**Comment by eliaslfox** [comment]
Is this a caching issue?

**Comment by stylewarning** [comment]
> Is this a caching issue?

I believe so. I'm not sure how or when or where the system detects when to download dependencies.

Presumably existing dependencies are cached and new ones aren't auto-downloaded.

**Comment by stylewarning** [comment]
@eliaslfox @colescott I modified the workflow to force a `quickload` on the test package... not sure if this is the best way to do things from a caching perspective, but it works.

**Review by eliaslfox — APPROVED** [review]
shipit

**Comment by eliaslfox** [comment]
My guess is that because the dependency is located in a separate asd file, it isn't invalidating the cache. This dependency is going to be pulled on every test run so it should be fixed soon.

If that is the issue, then either we use a single asd file or change the cache heuristics for the ci pipeline.

**Pull request merged**
