### PR TITLE
Remove usage of with-float-traps-masked

### LINKED ISSUE #816: Investigate `float-features:with-float-traps-masked` usage
This macro is used a lot in [library/math/elementary.lisp](https://github.com/coalton-lang/coalton/blob/main/library/math/elementary.lisp). Investigate if this is required.

### PR DESCRIPTION
**Pull request by eliaslfox**
Fixes #816

### CODE REVIEW

**Review by colescott — APPROVED** [review]

**Comment by stylewarning** [comment]
*the price is right sad sound*

What's the status of tests locally?

**Comment by eliaslfox** [comment]
The tests pass with float traps disabled. 

By default SBCL enabled some float traps. I tried to see if there was a commit explaining why, but it seems that the default float trap settings were inherited from CMUCL (see [src/code/cold-init.lisp](https://github.com/sbcl/sbcl/blob/a530bbe337109d898d5b4a001fc8f1afa3b5dc39/src/code/cold-init.lisp#L216-L219)).

SBCL's default float trap settings are in contrast to other environments like C which runs with float traps disabled, and Java which doesn't even support float traps.

We already had to disable float traps on CCL, this pr also disables them on SBCL.

**Comment by stylewarning** [comment]
@eliaslfox what about the CCL unit test?

**Comment by eliaslfox** [comment]
GitHub actions is broken. I'll restart it.

**Pull request merged**
