### PR TITLE
fix Unit matching, add Lisp-native Boolean type

### LINKED ISSUE #166: error matching against `Unit`
```
COALTON-USER> (coalton-codegen
                (define (f x)
                  (match x
                    ((Unit) 0))))
```

==>

```
Unknown symbol in match branch. UNIT is not a constructor.
in branch (UNIT)
in match on X
in definition of F
in COALTON-TOPLEVEL
```

### PR DESCRIPTION
**Pull request by stylewarning**
This fixes #166 and #145

### CODE REVIEW

**Comment by stylewarning** [comment]
I took the "easiest" route to getting pattern compilation to work, but I don't think it's the best way at the end.

I'd prefer that there be some way to generalize the `classname` arg to ctor-entries to allow for something more freeform; perhaps it can be an arbitrary Trivia pattern?

I think it deserves thought, but I don't think we need to nail it perfectly for this PR.

**Review by eliaslfox — APPROVED** [review]
This is kinda cursed.

**Comment by stylewarning** [comment]
I'm going to wait for @colescott to review as well, so he's in-the-loop about this.

**Comment by eliaslfox** [comment]
Don't merge this yet. I want to attempt to write a slightly less cursed version.

**Comment by eliaslfox** [comment]
#174 fixes this mostly. Coalton booleans still aren't lisp booleans but comparing symbols compiles to almost the same code as using cl:if on lisp booleans.

**Pull request closed without merging**
