### PR TITLE
Fix recursive calls

### LINKED ISSUE #125: Self-recursive functions dropping predicates on recursive call
Self recursive calls inside functions with predicates seem to be losing their predicates on the typed nodes.

Example:

```lisp
(define (f a b)
  (and (== a b)
       (f a b)))
```

produces the typed node binding

```
((F
            . #S(TYPED-NODE-ABSTRACTION
                 :TYPE EQ #T29484692 ⇒ (#T29484692 → #T29484692 → BOOLEAN)
                 :UNPARSED (FN (A B)
                             (AND (== A B) (F A B)))
                 :VARS ((A-793 . #T29484692) (B-794 . #T29484692))
                 :SUBEXPR #S(TYPED-NODE-APPLICATION
                             :TYPE EQ #T29484692 ⇒ BOOLEAN
                             :UNPARSED (AND (== A B) (F A B))
                             :RATOR #S(TYPED-NODE-VARIABLE
                                       :TYPE (BOOLEAN → BOOLEAN → BOOLEAN)
                                       :UNPARSED AND
                                       :NAME AND)
                             :RANDS (#S(TYPED-NODE-APPLICATION
                                        :TYPE EQ #T29484692 ⇒ BOOLEAN
                                        :UNPARSED (== A B)
                                        :RATOR #S(TYPED-NODE-VARIABLE
                                                  :TYPE EQ #T29484692 ⇒ (#T29484692 → #T29484692 → BOOLEAN)
                                                  :UNPARSED ==
                                                  :NAME ==)
                                        :RANDS (#S(TYPED-NODE-VARIABLE
                                                   :TYPE #T29484692
                                                   :UNPARSED A
                                                   :NAME A-793)
                                                #S(TYPED-NODE-VARIABLE
                                                   :TYPE #T29484692
                                                   :UNPARSED B
                                                   :NAME B-794)))
                                     #S(TYPED-NODE-APPLICATION
                                        :TYPE BOOLEAN
                                        :UNPARSED (F A B)
                                        :RATOR #S(TYPED-NODE-VARIABLE
                                                  :TYPE (#T29484692 → #T29484692 → BOOLEAN)
                                                  :UNPARSED F
                                                  :NAME F)
                                        :RANDS (#S(TYPED-NODE-VARIABLE
                                                   :TYPE #T29484692
                                                   :UNPARSED A
                                                   :NAME A-793)
                                                #S(TYPED-NODE-VARIABLE
                                                   :TYPE #T29484692
                                                   :UNPARSED B
                                                   :NAME B-794)))))
                 :NAME-MAP ((A-793 . A) (B-794 . B)))))
```

where the application of `F` should have type `EQ #T29484692 ⇒ (#T29484692 → #T29484692 → BOOLEAN)` but has type `(#T29484692 → #T29484692 → BOOLEAN)`.

### LINKED ISSUE #147: codegen (due to typesystem) bug for recursive function
I think I'm experiencing a codegen bug:

```
;; REPRO: this fails
(coalton-toplevel
  (define-type (String-Map :a)
    (SM-Alist (List (Tuple String :a))))

  (define (sm-add sm key val)
    (match sm
      ((SM-Alist alist)
       (let ((traverse (fn (current new updated)
                         (match current
                           ((Nil) (if updated
                                      new
                                      (Cons (Tuple key val)
                                            new)))
                           ((Cons x xs)
                            (match x
                              ((Tuple k _)
                               (if (== k key)
                                   (traverse xs (Cons (Tuple key val) new) True)
                                   (traverse xs (Cons x new) updated)))))))))
         (SM-Alist (traverse alist Nil False)))))))
```

This results in

```
; --> PROGN PROGN DEFUN PROGN SB-IMPL::%DEFUN SB-IMPL::%DEFUN 
; --> SB-INT:NAMED-LAMBDA FUNCTION THE PROGN BLOCK TRIVIA.LEVEL2:MATCH 
; --> TRIVIA.LEVEL2:MATCH2 TRIVIA.LEVEL2:MATCH2+ TRIVIA.LEVEL2:MATCH2*+ 
; --> SYMBOL-MACROLET TRIVIA.LEVEL1:MATCH1 LET BLOCK BLOCK LET 
; --> TRIVIA.LEVEL1:TRACE-WHEN WHEN IF LOCALLY LET RETURN-FROM LOCALLY 
; --> TRIVIA.LEVEL1:MATCH1 LET BLOCK BLOCK LET RETURN-FROM LOCALLY 
; --> LABELS COALTON-JSON::TRAVERSE-24 THE PROGN BLOCK 
; --> TRIVIA.LEVEL2:MATCH TRIVIA.LEVEL2:MATCH2 TRIVIA.LEVEL2:MATCH2+ 
; --> TRIVIA.LEVEL2:MATCH2*+ SYMBOL-MACROLET TRIVIA.LEVEL1:MATCH1 LET 
; --> BLOCK BLOCK LET TRIVIA.LEVEL1:TRACE-WHEN WHEN IF LOCALLY LET LET 
; --> RETURN-FROM LOCALLY TRIVIA.LEVEL1:MATCH1 LET BLOCK BLOCK LET 
; --> RETURN-FROM LOCALLY TRIVIA.LEVEL2:MATCH TRIVIA.LEVEL2:MATCH2 
; --> TRIVIA.LEVEL2:MATCH2+ TRIVIA.LEVEL2:MATCH2*+ SYMBOL-MACROLET 
; --> TRIVIA.LEVEL1:MATCH1 LET BLOCK BLOCK LET TRIVIA.LEVEL1:TRACE-WHEN 
; --> WHEN IF LOCALLY LET RETURN-FROM LOCALLY TRIVIA.LEVEL1:MATCH1 LET 
; --> BLOCK BLOCK LET RETURN-FROM LOCALLY TRIVIA.LEVEL2:MATCH 
; --> TRIVIA.LEVEL2:MATCH2 TRIVIA.LEVEL2:MATCH2+ TRIVIA.LEVEL2:MATCH2*+ 
; --> SYMBOL-MACROLET TRIVIA.LEVEL1:MATCH1 LET BLOCK BLOCK LET 
; --> TRIVIA.LEVEL1:TRACE-WHEN WHEN IF LOCALLY RETURN-FROM LOCALLY 
; --> TRIVIA.LEVEL1:MATCH1 LET BLOCK BLOCK LET RETURN-FROM LOCALLY 
; ==>
;   (COALTON-JSON::TRAVERSE-24 COALTON-JSON::XS-29
;    (COALTON-LIBRARY:CONS
;     (COALTON-LIBRARY:TUPLE COALTON-JSON::KEY-21 COALTON-JSON::VAL-22)
;     COALTON-JSON::NEW-26)
;    COALTON-LIBRARY:TRUE)
; 
; caught COMMON-LISP:WARNING:
;   function called with three arguments, but wants exactly four
;   See also:
;     The ANSI Standard, Section 3.2.2.3

; ==>
;   (COALTON-JSON::TRAVERSE-24 COALTON-JSON::XS-29
;    (COALTON-LIBRARY:CONS COALTON-JSON::X-28 COALTON-JSON::NEW-26)
;    COALTON-JSON::UPDATED-27)
; 
; caught COMMON-LISP:WARNING:
;   function called with three arguments, but wants exactly four
;   See also:
;     The ANSI Standard, Section 3.2.2.3
```

**However**, if I abstract out the alist searching functionality to its own function, it works:

```
;; this works
(coalton-toplevel
  (define (alist-insert alist key val)
    (let ((traverse (fn (current new updated)
                      (match current
                        ((Nil) (if updated
                                   new
                                   (Cons (Tuple key val)
                                         new)))
                        ((Cons x xs)
                         (match x
                           ((Tuple k _)
                            (if (== k key)
                                (traverse xs (Cons (Tuple key val) new) True)
                                (traverse xs (Cons x new) updated)))))))))
      (traverse alist Nil False)))

  (define-type (String-Map :a)
    (SM-Alist (List (Tuple String :a))))

  (define (sm-add sm key val)
    (match sm
      ((SM-Alist alist)
       (SM-Alist (alist-insert alist key val))))))
```

### LINKED ISSUE #216: Codegen bug in recursive polymorphic function
(Reported by Bike on Discord.)

```lisp
(define (%increases list count)
  (match list
    ((Cons x xs)
     (match xs
       ((Cons y _)
        (%increases xs (+ count (if (> y x) 1 0))))
       ((Nil) count)))
    ((Nil) count)))
```

> The first time I compile it I get "The function COMMON-LISP:NIL is called with two arguments, but wants exactly three" and subsequently I get "The function %INCREASES is called with two arguments, but wants exactly three" and I don't understand either warning.

This is probably similar to the previously reported codegen bugs, but I haven't investigated.

### PR DESCRIPTION
**Pull request by eliaslfox**
Fixes #216
Fixes #147
Fixes #125

### CODE REVIEW

**Review by colescott — APPROVED** [review]
Looks great!

**Comment by stylewarning** [comment]
Elias fixed it?!?!?!

woohoo!!!

**Comment by eliaslfox** [comment]
This might still be bugged on mutually recursive calls. *lolsob*

**Comment by stylewarning** [comment]
> This might still be bugged on mutually recursive calls. :/

Any test cases or just a hunch?

**Comment by eliaslfox** [comment]
just a guess

**Pull request merged**
