### PR TITLE
Print readably when *print-readably* is set

### LINKED ISSUE #707: Printed representation of Coalton types is not readable
The printed representation of Coalton types uses the `#.` macro in an attempt to be readable, but does not quote subobjects. This works fine for subobjects which are also Coalton types, or self-evaluating CL types, but breaks with lists (and would probably break with `repr :native symbol` objects).

E.g.

```
(coalton-toplevel
  (define-type ContainsList
    (ContainsList (List UFix))))

(cl:prin1-to-string (coalton (ContainsList (make-list 0 1 2))))
; => "#.(CONTAINSLIST (0 1 2))"

(cl:read-from-string (cl:prin1-to-string (coalton (ContainsList (make-list 0 1 2)))))
; in: CONTAINSLIST (0 1 2)
;     (0 1 2)
; 
; caught COMMON-LISP:ERROR:
;   illegal function call
; 
; compilation unit finished
;   caught 1 ERROR condition
```

Easy solution: stick a quote in front of each argument, so that `ContainsList` prints as `#.(CONTAINSLIST '(0 1 2))`.

### PR DESCRIPTION
**Pull request by eliaslfox**
Fixes #707

### CODE REVIEW

**Review by colescott — APPROVED** [review]

**Comment by stylewarning** [comment]
If the variable is off, maybe we should do away with #. entirely

**Comment by eliaslfox** [comment]
Yeah we could do that. I kinda like how it looks, but it does add noise.

**Comment by gefjon** [comment]
I believe `print-object` methods which rely on sharp-dot to `*print-readably*` are also supposed to check the value of `*read-eval*` and signal an error if it's false, and in the case of `(not (or *print-readably* *read-eval*))` one should not print a sharp-dot form.

**Comment by eliaslfox** [comment]
Read eval is fixed in #846

**Pull request merged**
