### PR TITLE
Matrix tests across safety 1 and 3

### PR DESCRIPTION
**Pull request by eliaslfox**
Add tests for safety 3 to detect issues like #199.

### CODE REVIEW

**Comment by eliaslfox** [comment]
These should be failing on safety 3. I'm not sure why they're failing on safety 1.

**Comment by stylewarning** [comment]
Will this have strange load-order or caching behavior?

I'm not sure if the compiler policy is being restricted early enough. Is Coalton getting loaded before the policy is being restricted?

**Comment by eliaslfox** [comment]
It might. I think I need to look more deeply into how the CI pipeline is configured.

**Comment by eliaslfox** [comment]
@stylewarning this is ready for review

**Review by stylewarning — APPROVED** [review]

**Pull request merged**
