### PR TITLE
Add explicit binding support to let forms

### LINKED ISSUE #13: Explicit bindings in LET blocks

### PR DESCRIPTION
**Pull request by colescott**
Let forms can now use declare similar to toplevel forms

Resolves #13

### CODE REVIEW

**Review by stylewarning — COMMENTED** [review]
Why not allow DECLARE in the "usual" Lisp spot in the body?

**Comment by colescott** [comment]
> Why not allow DECLARE in the "usual" Lisp spot in the body?

Allowing `declare` forms in subexpressions makes it so we can't do context-free parsing and would require a major reworking of the parsing system.

I also am partial to this because it is similar to the way you declare types for top level forms and is the way it is done in Haskell.

**Comment by stylewarning** [comment]
The syntax would be

```
<let-form> ::=
  (let (<binding>*)
    <decl>*
    <body>)

<binding> ::=
  (<symbol> <expr>)

<decl> ::=
  (declare <var> <type-expr>)
```

Critically, this is syntax. Nothing can "return" a `declare`, and `declare` cannot be mixed in with `<body>`. This is even what `alexandria:parse-body` parses out (except it looks for `cl:declare`). I don't understand what context dependence there is.

**Comment by colescott** [comment]
I guess "context-free parsing" isn't quite what I mean. With the current structure of the parser this will be hard to implement. 

Aside from implementation, the main issue I have with putting declares in the body the same way that lisp does it is that it means that type annotations, which in languages like Coalton act as a form of documentation, are separated from their respective values.

An example of this causing a bit of confusion is in a `let` with many forms such as
```
(let ((a some-long-form...)
      (b another-long-form...)
      (c another-form...))
  (declare a (Type :signature))
  (declare b (Complicated (Type Signature)))
  ...)
```
where it would be more helpful to someone reading the code to have it similar to how top level forms are annotated. 
```
(let ((declare a (Type :signature))
      (a some-long-form...)

      (declare b (Complicated (Type Signature)))
      (b another-long-form...)

      (c another-form...))
  ...)
```

I do agree that we should aim for the most lispy syntax, however I think in this case it leads to harder to read code and leads to inconsistencies with the existing syntax.

**Comment by stylewarning** [comment]
Alternative food 4 thought:

```
<binding> ::=
    (<var> <expr>)
  | (<var> :OF-TYPE <type-expr> := <expr>)
```

This would match CL:LOOP style and would make things align nicely.

Here are all the options splayed out:

```
(let ((declare x Integer)
      (x 2)
      (declare y (Num :a => :a -> :a))
      (y (+ (fromInt 1))))
  ...)

(let ((x 2)
      (y (+ (fromInt 1))))
  (declare x Integer)
  (declare y (Num :a => :a -> :a))
  ...)

(let ((x :of-type integer
         := 2)
        (y :of-type (Num :a => :a -> :a)
         := (+ (fromInt 1)))
  ...)
```

Upon inspection, I'm actually OK with any of them. Maybe I prefer the "Lisp" way most just because it's, well, the Lisp way.

**Comment by gefjon** [comment]
another option:
```
(let (((the Integer x) 2)
      ((the (Num :a => :a -> :a) y) (+ (fromInt 1))))
  ...)
```

**Comment by stylewarning** [comment]
Now that some options have aired out, I think I'm happy if @colescott makes the final decision.

**Comment by stylewarning** [comment]
Oh, if there's still time to squeeze a question in: How might we imagine declaring `fn` parameters? Good idea? No?

**Review by eliaslfox — APPROVED** [review]

**Pull request merged**
